### PR TITLE
add a DUB recipe to run the demo more easily

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
ping @Dechcaudron, i see that you are not watching your own repo.

**Comment by Dechcaudron** [comment]
Thanks for the heads-up @BBasile, I'm watching it now. I appreciate the PR, but I do not really understand what advantage there is to this. I also have 0 experience in embedding dub scripts within source code. Would you mind doing a quick explaining?

**Comment by ghost** [comment]
people can just run it.

**Comment by ghost** [comment]
`dub demo.d` and boom it works directly.

**Comment by Dechcaudron** [comment]
Polluting the demo script with the only benefit of being able to use `dub demo.d` instead of the current `dub -c demo` doesn't seem to be worth it IMHO. I'm sorry, but unless it provides some other advantage, I'll have to politely decline this PR.

**Pull request closed without merging**
